### ISSUE TITLE
Missing GetParameterTypes Service

### ISSUE THREAD

**Issue by wjwwood** [ros2/rcl_interfaces#1]
@esteve I think you need to merge the `review_results` branch. The Windows job (and I expect the other jobs) are failing with a missing include:

http://54.183.26.131:8080/job/ros2_batch_ci_windows/215/console

**Comment by esteve** [comment]
@tfoote is it ok to merge the `review_results` branch in `rcl_interfaces` ?

**Comment by tfoote** [comment]
+1 for merging review_results

**Comment by esteve** [comment]
Done.
