### ISSUE TITLE
Fail to subscribe /rosout topic

### ISSUE THREAD

**Issue by liueryun** [ros2/rcl_interfaces#124]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04

- Installation type:
  - binaries

- Version or commit hash:
  - eloquent
  
- DDS implementation:
  - the default DDS in binary
  
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

The way creating subscriber:
```
    log_sub_ = node_ptr_->create_subscription<rcl_interfaces::msg::Log>("/rosout", 10,
        std::bind(&TaiLogWidget::log_callback, this, std::placeholders::_1));

```
The callback function:
```
void TaiLogWidget::log_callback(const rcl_interfaces::msg::Log::SharedPtr log_msg_ptr)
{
    printf("got Log message!");
}
```

#### Actual behavior
The debug terminal displays:
```
realloc(): invalid pointer
```
I cannot event step into the callback function.

#### Additional information
It is OK to subscribe the "/rosout" topic with rclpy and get the expected Log message.

**Comment by clalancette** [comment]
Eloquent is End-of-Life as of [November 2020](http://docs.ros.org/en/rolling/Releases.html).  Please try again with Foxy (which you can build on 18.04, if you'd like), or Galactic.

I'm going to close this out for now, but if you are still having problems with it on a supported release, please feel free to open another issue.
