### ISSUE TITLE
Remove double-specification of default values in ParameterValue msg

### ISSUE THREAD

**Issue by dhood** [ros2/rcl_interfaces#19]
Default values were added explicitly in https://github.com/ros2/rcl_interfaces/pull/18 to prevent a valgrind error of uninitialised fields during serialisation. When messages can be created as pre-initialised with default values in client libraries, revert that PR and use default-initialised messages instead (to prevent specification of the default values in multiple locations).

Depends on https://github.com/ros2/ros2/issues/396
Connects to ros2/ros2#396

**Comment by mikaelarguedas** [comment]
#18 Needs to be reverted once https://github.com/ros2/ros2/issues/396 related PRs are merged.
@clalancette FYI, not sure if you want to "connect" them together

**Comment by clalancette** [comment]
@mikaelarguedas Thanks for the heads up; I'll connect this up with #396 as you suggest.
