### ISSUE TITLE
Change UUID type in action_msgs

### ISSUE THREAD

**Issue by jacobperron** [ros2/rcl_interfaces#49]
#### Feature description

Change type of `uuid` field in `GoalInfo.msg` to new message type defined in [unique_identifier_msgs](https://github.com/ros2/unique_identifier_msgs).

See [TODO in GoalInfo.msg](https://github.com/ros2/rcl_interfaces/blob/2a85883cf64d9dfbe9f15a43966bdb00819aac58/action_msgs/msg/GoalInfo.msg#L2).

Blocked by ros2/unique_identifier_msgs#1.

#### Implementation considerations

This will touch a few places in [rcl_action](https://github.com/ros2/rcl/tree/master/rcl_action), but the changes should only be minor.

We might also consider changing the type of UUIDs in the generated messages/services for actions; found in `rosidl_parser`:

https://github.com/ros2/rosidl/blob/075fe35bec2587d5c1012cb6ffec0db61c34277a/rosidl_parser/rosidl_parser/__init__.py#L799-L800

https://github.com/ros2/rosidl/blob/075fe35bec2587d5c1012cb6ffec0db61c34277a/rosidl_parser/rosidl_parser/__init__.py#L822-L823

https://github.com/ros2/rosidl/blob/075fe35bec2587d5c1012cb6ffec0db61c34277a/rosidl_parser/rosidl_parser/__init__.py#L845-L846

**Comment by hidmic** [comment]
@apojomovsky @jacobperron I propose we change the field name in `GoalInfo.msg` and friends to be `unique_identifier_msgs/UUID goal_id` so that code that uses it looks like `goal_id.uuid` instead of `uuid.uuid`.
