### ISSUE TITLE
Progress toward Quality Level 1

### ISSUE THREAD

**Issue by brawner** [ros2/rcl_interfaces#88]
This issue tracks the progression of packages in `rcl_interaces` that have been deemed necessary for Quality Level 1 and a 1.0 version level. It follows the outline described in [REP 2004](https://github.com/ros-infrastructure/rep/blob/c2ba03bac23b8f313e47820833fad000dbbe058b/rep-2004.rst). 

The packages slated for Quality Level 1 for ROS 2 Foxy are:
- action_msgs
- builtin_interfaces
- composition_interfaces
- lifecycle_msgs
- rcl_interfaces
- rosgraph_msgs
- statistics_msgs

Excluded for Quality Level 1 at this time:
- test_msgs

# Progress common to all packages:
* [x] Version Policy
    - Follows ROS Core Quality Declaration
* [x] Version >= 1.0.0
* [x] Change Control Process
    - Follows ROS Core
* [x] No testing required because these packages just define messages and services 

Documentation
* [x] Declared set of licenses
* [x] Copyright statement in each source file
    - Copyright statements aren't needed in msg/srv files

Dependencies:
* [x] non-ROS dependencies are equivalent level 1

Platform Support
* [x] Supports all tier 1 platforms

# Progress of specific packages
## action_msgs
Documentation
* [x] Per-feature documentation.
    - This feature documentation should also point to http://design.ros2.org/articles/actions.html 
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - builtin_interfaces
    - unique_identifier_msgs
* [x] non-ROS dependencies are equivalent level 1

## builtin_interfaces
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime

Specific comments/recommendations:
- Time.msg:
  - int64 for seconds (see #85)
  - sec -> seconds
  - nanosec -> nanoseconds

## composition_interfaces
Documentation
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime
    - rcl_interfaces

## lifecycle_msgs
Documentation
* [x] Per-feature documentation.
    - Should also point to lifecycle nodes documentation
* [x] Per-item documentation in public API. 
    - Needed in (ChangeState.srv, GetAvailableStates.srv, GetAvailableTransitions.srv, GetState.srv)
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - rosidl_default_runtime

## rcl_interfaces
* [x] Per-feature documentation.
* [x] Per-item documentation in public API. 
    - See below
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - builtin_interfaces
    - rosidl_default_runtime

## rosgraph_msgs
Documentation
* [x] Per-feature documentation
    - ROS 1 feature level docs exist
* [x] Per-item documentation in public API. 
* [x] Quality Declaration document

Dependencies:
* [x] Runtime "ROS" dependencies are level 1
    - builtin_interfaces
    - rosidl_default_runtime

**Comment by chapulina** [comment]
All packages are level 1 :smile: https://github.com/ros2/rcl_interfaces/pull/116
